# MkDocs configuration for PeruGuide AI Documentation

site_name: PeruGuide AI Documentation
site_description: Production-ready RAG system for Peru tourism information
site_author: Your Name
site_url: https://yourusername.github.io/peruguide-rag

repo_name: yourusername/peruguide-rag
repo_url: https://github.com/yourusername/peruguide-rag
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: red
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - Architecture:
    - Overview: architecture/overview.md
    - Feature Pipeline: architecture/feature-pipeline.md
    - Inference Pipeline: architecture/inference-pipeline.md
    - Evaluation: architecture/evaluation.md
  - API Reference:
    - Overview: api/overview.md
    - Endpoints: api/endpoints.md
    - Models: api/models.md
  - Development:
    - Setup: development/setup.md
    - Guidelines: development/guidelines.md
    - Testing: development/testing.md
    - Contributing: development/contributing.md
  - Deployment:
    - Docker: deployment/docker.md
    - Cloud: deployment/cloud.md
    - Monitoring: deployment/monitoring.md
  - Troubleshooting: troubleshooting.md
  - FAQ: faq.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/yourprofile
  version:
    provider: mike
